.github/workflows/pytest-all-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml

attempt to fix github action

---

.github/workflows/pytest-all-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml

GEOIO-102: run actions on pull request from forks

---

geoh5py/data/text_data.py
geoh5py/io/h5_reader.py
geoh5py/io/h5_writer.py
pyproject.toml
setup.py
tests/create_point_data_test.py
tests/user_comments_test.py

Replace reference to python 3.6 -> 3.7
Fix broken example for byte strings and add test for Text data as per: https://github.com/h5py/h5py/issues/379

GEOIO-100: Fix docs for 0.1.2

---

.github/workflows/pr_add_jira_summary.yml

**GEOPY-174 - on PR automatically add JIRA issue summary from JIRA number**

GEOPY-174: automatically add JIRA issue summary to PR

---

.github/workflows/pytest-windows.yml

**GEOPY-175 - bring back codecov on geoh5py**

GEOPY-175: fix condition to run CodeCov

---

geoh5py/__init__.py
pyproject.toml

**GEOPY-161 - release geoh5py 0.1.2**

GEOPY-161: bump version to 0.1.2

---

poetry.lock
pyproject.toml

GEOPY-195: update version of h5py

---

.pre-commit-config.yaml
README.rst
THIRD_PARTY_SOFTWARE.rst

**GEOPY-30 - third party notices and copyrights**

GEOPY-30: add copyright notices and statements for 3rd party

---

setup.py

**GEOPY-161 - release geoh5py 0.1.2** 
regenerated with dephell

GEOPY-161: update setup.py for h5py version

---

docs/content/user_guide/entities.ipynb
geoh5py/data/color_map.py
geoh5py/objects/drillhole.py
geoh5py/objects/octree.py
geoh5py/objects/points.py
geoh5py/workspace/workspace.py
tests/copy_entity_test.py

**GEOPY-228 - Error copying octree mesh** 
Fix issue with copy of octree and recarray vs ndarray with structure.

GEOPY-228: Error copying octree mesh

---

geoh5py/data/color_map.py
geoh5py/data/data_type.py
geoh5py/objects/object_base.py
poetry.lock

**GEOPY-248 - pylint fails  on development branch**

GEOPY-248: fix pylint errors

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml

**GEOPY-258 - change required test platforms per branch**

GEOPY-258: change required test platforms per branch

---

tests/insert_drillhole_data_test.py

**GEOPY-249 - Add fails on imported drillhole** 
Fix test for insertion at same depths

GEOPY-249 fixup

---

.pre-commit-config.yaml
geoh5py/interfaces/__init__.pyi
geoh5py/interfaces/api.pyi
geoh5py/interfaces/data.pyi
geoh5py/interfaces/groups.pyi
geoh5py/interfaces/objects.pyi
geoh5py/interfaces/shared.pyi
geoh5py/interfaces/workspace.pyi
pylintrc

**GEOPY-287 - apply pre-commit update** 
followup of https://github.com/MiraGeoscience/geoh5py/pull/107

GEOPY-287: run pre-commit update - followup

---

.github/workflows/static-analysis.yml
.pre-commit-config.yaml
tests/geoh5py_test.py

**GEOPY-288 - precommit in precommit-ci instead of github action**

GEOPY-288: precommit in precommit-ci instead of github action

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml

**GEOPY-298 - run pytest on Unix also for PR on develop branch**

GEOPY-298: run pytest on Unix also for PR on develop branch

---

docs/content/user_guide/entities.ipynb

Fix typos in doc of entities.ipynb

---

geoh5py/objects/drillhole.py

Addresses #117 
geoh5py.objects.drillhole.Drillhole.locations dtype inconsistency
Changed dtype of locations

Drillhole locations fix

---

geoh5py/data/data_type.py
geoh5py/groups/group_type.py
geoh5py/io/h5_writer.py
geoh5py/objects/drillhole.py
geoh5py/objects/object_base.py
geoh5py/objects/object_type.py
geoh5py/shared/entity.py
geoh5py/workspace/workspace.py
tests/set_parent_test.py

**GEOPY-246 - Parent change not reflected in GA tree**

GEOPY-246: Parent change

---

geoh5py/objects/surveys/direct_current.py
tests/create_survey_dcip_test.py

**GEOPY-312 - Increase geoh5py coverage**

GEOPY-312: Increase coverage of dc object

---

geoh5py/workspace/workspace.py
tests/create_entity_parent_test.py

**GEOPY-312 - Increase geoh5py coverage**

GEOPY-312: Fix input argument parent=None

---

.github/workflows/pr_add_jira_summary.yml

**GEOPY-407 - add_jira_summary pipeline is failing on github** 
copy fixes from https://github.com/MiraGeoscience/geoapps/pull/234

GEOPY-407: add_jira_summary pipeline is failing on github

---

docs/content/release_notes.rst
geoh5py/__init__.py
geoh5py/objects/surface.py
pyproject.toml
tests/copy_entity_test.py
tests/create_surface_data_test.py

**GEOPY-411 - release geopy 0.1.6**

GEOPY-411: Prep for release 0.1.6

---

geoh5py/shared/exceptions.py
geoh5py/shared/validators.py
geoh5py/ui_json/templates.py
tests/ui_json_test.py

**GEOPY-347 - ui json parsing and validation in geoh5py**

GEOPY-347: Reorganize custom validations and tests

---

geoh5py/shared/exceptions.py
geoh5py/shared/validators.py
geoh5py/ui_json/__init__.py
geoh5py/ui_json/input_file.py
geoh5py/ui_json/validation.py
tests/ui_json_test.py

**GEOPY-347 - ui json parsing and validation in geoh5py**
Allow passing validations and validators into InputValidation class.  Move validations from ui_json into InputValidations class.

Geopy 347 reorganize

---

geoh5py/ui_json/utils.py
tests/ui_json_utils_test.py

**GEOPY-514 - The AtLeastOneValidation doesn't work for the natural sources**

Change logic on dependency variables

---

docs/content/api/geoh5py.rst
docs/content/api/geoh5py.ui_json.rst
docs/content/geoh5_format/analyst/data.rst
docs/content/geoh5_format/analyst/groups.rst
docs/content/geoh5_format/analyst/objects.rst
docs/content/geoh5_format/hierarchy.rst
docs/content/geoh5_format/integrator/data.rst
docs/content/uijson_format/index.rst
docs/content/uijson_format/json_objects.rst
docs/content/user_guide/core_entities.ipynb
geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py

**GEOPY-461 - Documentation: Fix example for BlockModel**

GEOPY-461: Update block model documentation to include origin

---

geoh5py/workspace/workspace.py
tests/workspace_context_test.py

**GEOPY-574 - Allow workspace.open() as context**

GEOPY-574: Make open return self. Augment unit test

---

.github/workflows/codeql-analysis.yml
.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml
.pre-commit-config.yaml
geoh5py/data/data.py
geoh5py/data/float_data.py
geoh5py/data/numeric_data.py
geoh5py/objects/object_base.py
geoh5py/objects/surveys/electromagnetics/airborne_tem.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/magnetotellurics.py
geoh5py/objects/surveys/magnetics.py
geoh5py/shared/entity_type.py
geoh5py/shared/validators.py
geoh5py/workspace/workspace.py
poetry.lock
pylintrc
pyproject.toml
tests/weakref_test.py
tests/weakref_utils_test.py

**GEOPY-587 - fix new pylint reports in geoh5py**

GEOPY-587: fix new pylint reports in geoh5py

---

geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py
tests/validators_test.py

**GEOPY-556 - Make all jupyter apps read-only**

GEOPY-556: Make all jupyter apps read-only

---

geoh5py/workspace/workspace.py
tests/delete_entity_test.py

**GEOPY-608 - Check for allow_delete before delete entity**

GEOPY-608: Add check for allow_delete. Raise error, update unittest

---

geoh5py/data/numeric_data.py
geoh5py/io/h5_writer.py
geoh5py/shared/concatenation.py
geoh5py/workspace/workspace.py
tests/create_drillhole_v4_0_test.py
tests/data_instantiation_test.py

**GEOPY-583 - Error removing concatenated entity**

GEOPY-583: Error removing concatenated entity

---

docs/conf.py
docs/content/release_notes.rst
geoh5py/__init__.py
geoh5py/ui_json/input_file.py
pyproject.toml
setup.py

**GEOPY-616 - Release geoh5py 0.3.1**

Geopy 616b

---

geoh5py/objects/curve.py
geoh5py/objects/object_base.py
geoh5py/objects/points.py
geoh5py/objects/surface.py
tests/create_curve_data_test.py
tests/create_point_data_test.py
tests/create_surface_data_test.py

**GEOPY-624 - Add method to safely add remove vertices**

GEOPY-624:  Add method to safely add remove vertices

---

docs/conf.py
geoh5py/__init__.py
pyproject.toml
setup.py

**GEOPY-662 - Release geoh5py-0.5.0**

GEOPY-662 remove alpha from version 0.5.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml
.gitignore
.idea/scopes/sources.xml
poetry.lock
pyproject.toml
tests/requirements.txt

**GEOPY-674 - update github actions and devtools scripts**

GEOPY- 674: update github actions and devtools scripts

---

.github/workflows/codeql-analysis.yml
.github/workflows/pr_add_jira_summary.yml
.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml

**GEOPY-674 - update github actions and devtools scripts**

GEOPY-674: more update in github actions

---

.github/dependabot.yml

for actions, scheduled monthly

Configure dependabot version update

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml

**GEOPY-834 - kill running github actions upon new commit**
kill running github action upon new commit on the same PR

GEOPY-834: kill running github actions the same PR

---

docs/conf.py
geoh5py/__init__.py
pyproject.toml
setup.py

GEOPY-850 change version to 0.6.1

---

README.rst

**GEOPY-862 - measure maintainability with code climate**

GEOPY-862: measure maintainability with code climate

---

.github/workflows/static-analysis.yml
.pre-commit-config.yaml
geoh5py/objects/block_model.py
geoh5py/objects/grid2d.py
geoh5py/objects/octree.py
geoh5py/objects/surveys/direct_current.py
poetry.lock
pyproject.toml

**GEOPY-857 - clip by extent fails with memory error on large file**

GEOPY-857: fix proposal for numpy array to float scalar

---

geoh5py/io/h5_writer.py
geoh5py/shared/concatenation.py
geoh5py/workspace/workspace.py
tests/drillhole_v4_0_test.py

**GEOPY-876 - Validate geoh5 format when using 4.2 save as to 4.1**

GEOPY-876: validate geoh5 format when using 4.2 save as to 4.1

---

docs/content/release_notes.rst

**GEOPY-878 - Release geoh5py v0.7.0**

GEOPY-878: Release 0.7.0

---

geoh5py/objects/__init__.py
geoh5py/objects/surveys/electromagnetics/airborne_fem.py
geoh5py/objects/surveys/electromagnetics/airborne_tem.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/ground_tem.py
geoh5py/objects/surveys/electromagnetics/magnetotellurics.py
geoh5py/objects/surveys/electromagnetics/tipper.py
tests/survey_fem_test.py

**GEOPY-741 - Airborne FEM survey**

GEOPY-741- Airborne FEM survey

---

geoh5py/objects/surveys/electromagnetics/ground_fem.py

GEOPY-747: Update uuids for large-loop surveys

---

geoh5py/objects/geo_image.py
geoh5py/objects/grid2d.py
geoh5py/shared/utils.py
tests/clip_cell_data_test.py
tests/geo_image_test.py
tests/grid_2d_test.py

**GEOPY-1002 - dip and rotation**
Now, the crop grid 2d take account the dip
The vertical is now correlated with the dip

Changing the grid2d dip.

---

geoh5py/data/boolean_data.py

**GEOPY-776 - Support masking attributes**
converting to int8
Note: the no data values property makes no sense for boolean.
Should it be False instead of shared.NDV?

better managing of potential no data values

---

geoh5py/objects/drape_model.py

**GEOPY-1025 - Improve docs strings for drape_model object**

Update doctstrings for prisms and layers properties

---

.github/workflows/pytest-windows.yml
pyproject.toml

**GEOPY-882 - geoh5py not uploading to codecov**

GEOPY-882 try to fix codecov report

---

geoh5py/objects/geo_image.py
geoh5py/shared/conversion/grid2d.py
geoh5py/shared/utils.py
tests/geo_image_test.py

**GEOPY-1014 - Crop geoimage by extent yields large files. Look into compression format of PIL**
geoimage compression.
Geoimage is now a png file.

Geopy 1014

---

geoh5py/data/numeric_data.py
geoh5py/io/h5_writer.py
geoh5py/shared/concatenation.py
tests/drillhole_v4_0_test.py

**GEOPY-1030 - Concatenated drillhole data stored in property group can have different lengths when it should be collocated**

GEOPY-1030

---

geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/cell_object.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation.py
geoh5py/shared/entity.py
geoh5py/workspace/workspace.py
tests/delete_entity_test.py
tests/property_group_test.py
tests/survey_fem_test.py
tests/survey_mt_test.py
tests/survey_tem_test.py
tests/ui_json_test.py

**GEOPY-438 - Allow property_groups query from workspace.get_entity**
pass property groups to children.
Changes in a bunch of files and in the tests.

add PropertyGroup to objects children

---

geoh5py/groups/property_group.py
geoh5py/objects/object_base.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/shared/concatenation.py

**GEOPY-1035 - Crash on Airborne TEM selection**

GEOPY-1035

---

geoh5py/io/h5_writer.py
geoh5py/objects/object_base.py
geoh5py/workspace/workspace.py

**GEOPY-1017 - Profile OMF large file conversion**

GEOPY-1017

---

geoh5py/shared/concatenation.py
tests/drillhole_v4_0_test.py

**GEOPY-1055 - ConcatenatedDrillhole object from and to properties don't handle empty property list correctly**

GEOPY-1055

---

geoh5py/ui_json/utils.py

**GEOPY-1039 - create uijson for curve depth mapper**

add group type to monitory_directory_copy

---

geoh5py/shared/concatenation.py
tests/drillhole_v4_0_test.py

**GEOPY-1067 - Error reading concatenated property_groups**

GEOPY-1067

---

docs/conf.py
docs/content/release_notes.rst
geoh5py/__init__.py
pyproject.toml

**GEOPY-1024 - Release geoh5py-0.8.0**

GEOPY-1024

---

geoh5py/shared/exceptions.py
geoh5py/ui_json/enforcers.py
geoh5py/ui_json/forms.py
geoh5py/ui_json/parameters.py
geoh5py/ui_json/ui_json.py
tests/ui_json/enforcers_test.py
tests/ui_json/exceptions_test.py
tests/ui_json/forms_test.py
tests/ui_json/parameter_test.py
tests/ui_json/uijson_test.py

**GEOPY-1068 - Add RequiredEnforcer class to validate label/value exist in all FormParameters**

GEOPY-1068

---

geoh5py/data/data_type.py
geoh5py/io/h5_writer.py
geoh5py/objects/surveys/electromagnetics/base.py
tests/survey_tem_test.py

**GEOPY-1080 - Value map not updated**

GEOPY-1080

---

geoh5py/ui_json/forms.py
geoh5py/ui_json/ui_json.py
tests/ui_json/forms_test.py
tests/ui_json/uijson_test.py

**GEOPY-1074 - Create UIJson parameter level validations **

GEOPY-1074

---

geoh5py/groups/property_group.py
tests/property_group_test.py

**GEOPY-1092 - create a property_group.collect_values()**
add a property group values collector

GEOPY-1092

---

geoh5py/shared/merging/drape_model.py

**GEOPY-1045 - Merge DrapeModel objects**

GEOPY-1045b: Build index map

---

geoh5py/objects/object_base.py
geoh5py/shared/entity_type.py
geoh5py/shared/merging/base.py
tests/merger_drape_model_test.py
tests/merger_test.py

**GEOPY-1102 - merge curves**
add one object merger

Geopy 1102 corr2

---

geoh5py/data/visual_parameters.py
geoh5py/objects/drillhole.py
geoh5py/objects/geo_image.py
pylintrc

**GEOPY-1161 - Release geoh5py 0.8.0rc2**

GEOPY-1161

---

geoh5py/shared/concatenation.py
geoh5py/shared/utils.py

**GEOPY-1032 - Profile read/write of las conversion**

GEOPY-1032: Profile read/write of las conversion

---

geoh5py/shared/concatenation.py
geoh5py/shared/utils.py

**GEOPY-1032 - Profile read/write of las conversion**

1032-to-release/0.8.0

---

geoh5py/shared/utils.py

**GEOPY-1187 - Test failing on geoh5py develop branch**

GEOPY-1187: Test failing on geoh5py develop branch

---

geoh5py/shared/concatenation.py
tests/drillhole_v4_0_test.py

**GEOPY-1147 - Increment property group for data with new depth sampling**

GEOPY-1147

---

.github/workflows/pr_add_jira_summary.yml

**GEOPY-941 - auto-update PR title in github from issue number**

GEOPY-941: auto-update PR title from issue number

---

geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/drillholes_group_table.py
tests/drillhole_v4_0_test.py

**GEOPY-1296 - geoh5py: export data in vectorial form in Drillholes PropertyGroup**
patch: minor change fixing a bug

GEOPY-1296: 1296_patch

---

geoh5py/data/boolean_data.py
tests/boolean_test.py

**GEOPY-1328 - Issue loading Bool data in mode="r"**

GEOPY-1328: Issue loading Bool data in mode="r"

---

geoh5py/io/h5_reader.py
geoh5py/io/h5_writer.py
geoh5py/shared/concatenation/drillhole.py
geoh5py/shared/concatenation/property_group.py
geoh5py/workspace/workspace.py
tests/drillhole_v4_0_test.py

**GEOPY-1349 - get_data() does not work consistently with concatenatedPropertyGroup**

GEOPY-1349: get_data() does not work consistently with concatenatedPropertyGroup

---

geoh5py/groups/group.py
geoh5py/groups/property_group.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/object.py
geoh5py/shared/entity_container.py
geoh5py/shared/utils.py
tests/drillhole_v4_0_test.py

**GEOPY-1346 - cannot removed concatenated data using object.remove() method**

GEOPY-1346: cannot removed concatenated data using object.remove() method

---

geoh5py/shared/utils.py

**GEOPY-1423 - Issue with workspace on compute_trigger of edge detection app**

GEOPY-1423: Remove unnecessary line

---

geoh5py/ui_json/utils.py
tests/ui_json_test.py
tests/ui_json_utils_test.py

**GEOPY-1286 - Make refinement "surface" -> layers optional**

GEOPY-1286: Make refinement "surface" -> layers optional

---

geoh5py/shared/concatenation/object.py

**GEOPY-1414 - add property group suffix to las export files**

GEOPY-1414: add property group suffix to las export files

---

geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py

**GEOPY-1441 - Suppress unnecessary warnings triggered in set_enabled  **

GEOPY-1441: Suppress unnecessary warnings triggered in set_enabled  

---

geoh5py/io/h5_reader.py
geoh5py/io/h5_writer.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/drillholes_group_table.py

**GEOPY-1434 - pushing back drillholegroup back using monitoring directory + drag and drop uijson raise errors**

GEOPY-1434: pushing back drillholegroup back using monitoring directory + drag and drop uijson raise errors

---

geoh5py/data/data_type.py
geoh5py/objects/curve.py
tests/curve_data_test.py

**GEOPY-532 - Unordered parts are slowing done import from Analyst**

GEOPY-532: Unordered parts are slowing done import from Analyst

---

geoh5py/data/data_type.py
geoh5py/data/reference_value_map.py
geoh5py/io/h5_writer.py
geoh5py/objects/octree.py

**GEOPY-1440 - geoh5py accepot any kind of integer**
change int32 to np.integer to prevent bugs if np.int64 is used

GEOPY-1440: geoh5py accepot any kind of integer

---

geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/object.py
geoh5py/shared/concatenation/property_group.py
geoh5py/shared/entity_container.py
geoh5py/workspace/workspace.py
tests/drillhole_v4_0_test.py
tests/property_group_test.py

**GEOPY-1418 - Clean out empty property groups on drillhole objects after data removal**

GEOPY-1418: Clean out empty property groups on drillhole objects after data removal

---

geoh5py/data/data.py
geoh5py/io/h5_reader.py
geoh5py/shared/concatenation/concatenator.py
tests/drillhole_v4_0_test.py

**GEOPY-1439 - data FileData  associated to drillhole_group is not accessible. **

GEOPY-1439: data FileData  associated to drillhole_group is not accessible. 

---

geoh5py/io/h5_writer.py
geoh5py/workspace/workspace.py
tests/drillhole_v4_0_test.py

**GEOPY-1418 - Clean out empty property groups on drillhole objects after data removal**

GEOPY-1418: Avoid removing empty arrays

---

geoh5py/objects/cell_object.py
geoh5py/objects/object_base.py
geoh5py/objects/points.py
tests/curve_data_test.py

**GEOPY-1460 - Crash on remove_vertices of points object**
correct the remove vertices bug

GEOPY-1460: Crash on remove_vertices of points object

---

pyproject.toml

**GEOPY-1472 - build distribution files for geology and geophysics modules for Analyst**

GEOPY-1472: update links to homepage, doc, maintainers

---

geoh5py/objects/octree.py
tests/octree_test.py

**GEOPY-1503 - Octree mesh cell definition not update if rec array**

GEOPY-1503: Octree mesh cell definition not update if rec array

---

geoh5py/groups/uijson.py
geoh5py/shared/entity_container.py
geoh5py/shared/utils.py
geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py
tests/group_test.py
tests/shared_utils_test.py

**GEOPY-1530 - Use UIJson group **

GEOPY-1530: Use UIJson group 

---

geoh5py/shared/utils.py
geoh5py/ui_json/input_file.py

**GEOPY-1530 - Use UIJson group **

GEOPY-1530: Convert nan first

---

.github/workflows/pytest-windows.yml
pyproject.toml

**GEOPY-1564 - CodeCov is failing on public repos**

GEOPY-1564: CodeCov is failing on public repos

---

docs/content/release_notes.rst

**GEOPY-1559 - Update docs for all release branches**

GEOPY-1559: Update docs for all release branches

---

geoh5py/groups/__init__.py
geoh5py/groups/base.py
geoh5py/groups/container.py
geoh5py/groups/custom.py
geoh5py/groups/drillhole.py
geoh5py/groups/giftools.py
geoh5py/groups/group_type.py
geoh5py/groups/integrator.py
geoh5py/groups/maps.py
geoh5py/groups/notype.py
geoh5py/groups/root.py
geoh5py/groups/simpeg.py
geoh5py/groups/survey.py
geoh5py/groups/uijson.py
geoh5py/io/h5_writer.py
geoh5py/objects/object_base.py
geoh5py/objects/octree.py
geoh5py/shared/entity.py
geoh5py/shared/entity_container.py
geoh5py/shared/utils.py
geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py
geoh5py/workspace/workspace.py
tests/group_test.py
tests/octree_test.py
tests/point_data_test.py
tests/shared_utils_test.py
tests/ui_json_test.py

**GEOPY-1620: geoh5py develop branch lost fixes around drillhole group**
Revert "Revert "Merge branch 'update_release' into GEOPY-1562
This reverts commit 9015aa1d9acf276a5b498eeba460c063db4cba0c.
-	pyproject.toml

GEOPY-1620: geoh5py develop branch lost fixes around drillhole group

---

tests/curve_data_test.py

**GEOPY-1591 - unstable test test_cell_from_part **

GEOPY-1591: unstable test test_cell_from_part 

---

.pre-commit-config.yaml
pyproject.toml

**GEOPY-1697 - use pydantic plugin for mypy**
adding the pydantic plugin for mypy in pre-commit

GEOPY-1697: use pydantic plugin for mypy

---

.pre-commit-config.yaml
geoh5py/data/color_map.py
geoh5py/data/data.py
geoh5py/data/data_type.py
geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/cell_object.py
geoh5py/objects/object_base.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/drillhole.py
geoh5py/shared/concatenation/object.py
geoh5py/shared/entity.py
geoh5py/shared/entity_container.py
geoh5py/shared/entity_type.py
geoh5py/shared/exceptions.py
geoh5py/shared/utils.py
geoh5py/shared/validators.py
geoh5py/ui_json/forms.py
geoh5py/ui_json/validation.py
geoh5py/workspace/workspace.py
pylintrc
tests/delete_entity_test.py
tests/drillhole_v4_0_test.py
tests/modify_property_group_test.py
tests/property_group_test.py
tests/remove_root_test.py
tests/shared_utils_test.py
tests/workspace_test.py

**GEOPY-1656 - Always check/closed EM loops and return warning**

GEOPY-1656: Always check/closed EM loops and return warning

---

geoh5py/objects/drape_model.py
tests/drape_model_test.py

**GEOPY-1710 - Find more efficient computation for DrapeModel centroids**

GEOPY-1710: Find more efficient computation for DrapeModel centroids

---

geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/drillhole.py
geoh5py/shared/exceptions.py
geoh5py/shared/validators.py
tests/property_group_test.py
tests/ui_json_test.py
tests/validators_test.py

**GEOPY-1664 - Property group type validation is broken**

GEOPY-1664: Property group type validation is broken

---

geoh5py/data/data_type.py
geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/cell_object.py
geoh5py/objects/curve.py
geoh5py/objects/drillhole.py
geoh5py/objects/octree.py
geoh5py/objects/points.py
geoh5py/objects/surveys/electromagnetics/tipper.py
geoh5py/shared/exceptions.py
geoh5py/shared/validators.py
tests/curve_data_test.py
tests/octree_test.py
tests/point_data_test.py
tests/property_group_test.py
tests/surface_data_test.py
tests/ui_json_test.py
tests/validators_test.py

**GEOPY-1645 - Update for geoh5py refactor of class instantiation**

GEOPY-1645: Update for geoh5py refactor of class instantiation

---

geoh5py/data/blob_data.py
geoh5py/data/color_map.py
geoh5py/data/data.py
geoh5py/data/filename_data.py
geoh5py/data/geometric_data.py
geoh5py/data/numeric_data.py
geoh5py/data/referenced_data.py
geoh5py/data/text_data.py
geoh5py/data/unknown_data.py
geoh5py/data/visual_parameters.py
geoh5py/groups/base.py
geoh5py/io/h5_reader.py
geoh5py/io/h5_writer.py
geoh5py/objects/drillhole.py
geoh5py/objects/geo_image.py
geoh5py/objects/object_base.py
geoh5py/shared/entity_container.py
tests/add_filename_data_test.py
tests/boolean_test.py
tests/geo_image_test.py
tests/user_comments_test.py

**GEOPY-1668 - Continue refactoring on Data classes.**

GEOPY-1668: Continue refactoring on Data classes.

---

geoh5py/io/h5_writer.py

**GEOPY-1738 - Crash handling GI queries**

GEOPY-1738: Crash handling GI queries

---

geoh5py/objects/surveys/electromagnetics/base.py

**GEOPY-1749 - Point simpeg-driver to geoh5py feature 0.10.0**

GEOPY-1749: Point simpeg-driver to geoh5py feature 0.10.0

---

geoh5py/data/data_type.py
geoh5py/workspace/workspace.py

**GEOPY-1738 - Crash handling GI queries**

GEOPY-1738: _r2

---

geoh5py/ui_json/utils.py

**GEOPY-1760 - Fix required based on logic dependent**

GEOPY-1760: Fix required based on logic dependent

---

geoh5py/data/data_type.py
geoh5py/data/referenced_data.py
tests/reference_data_test.py

**GEOPY-1720 - Fix handling of geometric data from reference data table with user names**

GEOPY-1720: _r2

---

.github/workflows/python_analysis.yml
geoh5py/data/data_type.py
geoh5py/data/reference_value_map.py
geoh5py/data/referenced_data.py
geoh5py/io/h5_reader.py
geoh5py/objects/cell_object.py
geoh5py/objects/object_base.py
geoh5py/objects/points.py
tests/reference_data_test.py
tests/survey_tem_test.py

**GEOPY-1767 - Support Value map with bytes**

GEOPY-1767: Support Value map with bytes

---

.github/workflows/python_analysis.yml
pyproject.toml

**GEOPY-1712 - disable RUF005 as it is wrong with numpy array**

GEOPY-1712: Exclude RUFF005

---

geoh5py/groups/property_group.py
geoh5py/io/h5_reader.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation/object.py
geoh5py/shared/concatenation/property_group.py
tests/drillhole_v4_0_test.py
tests/merger_test.py
tests/property_group_test.py

**GEOPY-1755 - create an object to access all the data of a property group in a recarray**

GEOPY-1755: Property group refactor

---

geoh5py/ui_json/utils.py

**GEOPY-1774 - Re-order the inversion inputs following users comments**

GEOPY-1774: Re-order the inversion inputs following users comments

---

.pre-commit-config.yaml
geoh5py/objects/drillhole.py
tests/drillhole_v4_0_test.py

**GEOPY-1781 - tests of las-goh5 fail with geoh5 0.10.0**

GEOPY-1781: tests of las-goh5 fail with geoh5 0.10.0

---

geoh5py/data/data.py
geoh5py/data/data_type.py
geoh5py/groups/base.py
geoh5py/groups/property_group.py
geoh5py/io/h5_writer.py
geoh5py/objects/cell_object.py
geoh5py/objects/drillhole.py
geoh5py/objects/geo_image.py
geoh5py/objects/grid2d.py
geoh5py/objects/object_base.py
geoh5py/objects/octree.py
geoh5py/objects/points.py
geoh5py/objects/surveys/direct_current.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/tipper.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/entity.py
geoh5py/shared/entity_container.py
geoh5py/shared/entity_type.py
geoh5py/shared/utils.py
geoh5py/ui_json/input_file.py
geoh5py/ui_json/templates.py
geoh5py/workspace/workspace.py
pyproject.toml

**GEOPY-1802 - Copying drillhole groups crashes**

GEOPY-1802: Copying drillhole groups crashes

---

geoh5py/groups/property_group.py
geoh5py/groups/property_group_type.py
geoh5py/io/h5_writer.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation/object.py
geoh5py/shared/concatenation/property_group.py
tests/monitored_update_test.py
tests/property_group_test.py

**GEOPY-1165 - Check for properties for Property Group Type - Implement Property Group Type: Simple**
Reverting to Enum

GEOPY-1165: b

---

geoh5py/objects/cell_object.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/magnetotellurics.py
geoh5py/objects/surveys/electromagnetics/tipper.py
tests/survey_airborne_tem_test.py
tests/survey_ground_tem_test.py
tests/survey_tem_test.py

**GEOPY-1811 - Use latest "Tx ID tx property" on ground EM metadata. **

GEOPY-1811: Use latest "Tx ID tx property" on all EM surveys. 

---

geoh5py/groups/property_group.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation/object.py
tests/property_group_test.py

**GEOPY-1822 - update The names of PropertyGroup if it already exists**
ensure Names are unique for property_group

GEOPY-1822: update The names of PropertyGroup if it already exists

---

geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/tipper.py
tests/survey_airborne_tem_test.py
tests/survey_fem_test.py
tests/survey_ground_tem_test.py
tests/survey_tipper_test.py

**GEOPY-1811 - Use latest "Tx ID tx property" on ground EM metadata. **

GEOPY-1811: b

---

geoh5py/objects/drillhole.py
tests/drillhole_data_test.py

**GEOPY-1814 - Issue reading single drillhole exported from DrillholeGroup**

GEOPY-1814: Issue reading single drillhole exported from DrillholeGroup

---

geoh5py/io/h5_writer.py
tests/metadata_test.py

**GEOPY-1623 - metadata are not displaying when exporting metadata to drillhole group**

GEOPY-1623: metadata are not displaying when exporting metadata to drillhole group

---

.github/workflows/python_deploy_dev.yml
.github/workflows/python_deploy_prod.yml
geoh5py/io/h5_writer.py
geoh5py/objects/drillhole.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/tipper.py
geoh5py/shared/concatenation/concatenator.py
meta.yaml
poetry.lock
tests/drillhole_data_test.py
tests/metadata_test.py
tests/survey_airborne_tem_test.py
tests/survey_fem_test.py
tests/survey_ground_tem_test.py
tests/survey_tipper_test.py

RELEASE-0: Develop release 0 10

---

geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/utils.py
geoh5py/ui_json/forms.py
geoh5py/ui_json/input_file.py
geoh5py/ui_json/utils.py
geoh5py/ui_json/validation.py
geoh5py/workspace/workspace.py
tests/ui_json_test.py
tests/ui_json_utils_test.py

**GEOPY-1846 - pass drillholes group in InputFile data**

GEOPY-1846: pass drillholes group in InputFile data

---

geoh5py/objects/octree.py
tests/octree_test.py

**GEOPY-1820 - Add a depth of investigation application**

GEOPY-1820: Add a depth of investigation application

---

geoh5py/data/reference_value_map.py
tests/reference_data_test.py

**GEOPY-1878 - Error creating value map from values**

GEOPY-1878: Error creating value map from values

---

geoh5py/workspace/workspace.py
tests/workspace_test.py

**GEOPY-1910 - Throw warning if any of the common auto-saving drive is found in mode="r+"**

GEOPY-1910: Throw warning if any of the common auto-saving drive is found in mode="r+"

---

geoh5py/objects/grid_object.py
geoh5py/objects/octree.py

**GEOPY-1946 - Octree mesh upside down**

GEOPY-1946: Octree mesh upside down

---

.github/workflows/issue_to_jira.yml
recipe.yaml

**DEVOPS-654 - broken automation creating JIRA issue from GitHub issue**

DEVOPS-654: specify components in issue_to_jira workflow

---

geoh5py/data/data_type.py
geoh5py/data/reference_value_map.py
geoh5py/data/referenced_data.py
geoh5py/objects/object_base.py
geoh5py/workspace/workspace.py
tests/merger_drape_model_test.py
tests/reference_data_test.py

**GEOPY-2033 - Error copying reference data with GeometryDataValueMap**

GEOPY-2033: Error copying reference data with GeometryDataValueMap

---

geoh5py/io/h5_writer.py

**GEOPY-2065 - Crash on monitoring directory copy with reference data**

GEOPY-2065: Crash on monitoring directory copy with reference data

---

geoh5py/data/numeric_data.py
tests/numeric_data_test.py
tests/point_data_test.py

**GEOPY-2039 - Deal with data values vector of wrong length**
avoid raising a bug if values are too long and truncate them like GA

GEOPY-2039: Deal with data values vector of wrong length

---

geoh5py/ui_json/ui_json.py
tests/ui_json/uijson_test.py

**GEOPY-2035 - Preserve unknown (extra) fields in UIJson from ui.json file**

GEOPY-2035: Preserve unknown (extra) fields in UIJson from ui.json file

---

geoh5py/ui_json/annotations.py
tests/ui_json/uijson_test.py

**GEOPY-2056 - Handle extra fields and deprecations in UIJson version validation**
…ther packages

GEOPY-2056: Handle extra fields and deprecations in UIJson version validation

---

geoh5py/shared/validators.py
geoh5py/ui_json/forms.py
geoh5py/ui_json/ui_json.py

**GEOPY-2068 - Clean up pydantic warnings**

GEOPY-2068: Clean up pydantic warnings

---

geoh5py/data/colour.py
tests/coulour_test.py

**GEOPY-2053 - Support colour data type**
change the nan values by the default nan values for the full color using a mask

GEOPY-2053: Support colour data type

---

geoh5py/io/h5_writer.py
geoh5py/objects/__init__.py
geoh5py/objects/text.py
geoh5py/shared/entity_container.py
geoh5py/shared/utils.py
tests/text_object_test.py

**GEOPY-1900 - Implement Text Data object**

GEOPY-1900: Implement Text Data object

---

geoh5py/data/reference_value_map.py
tests/reference_data_test.py

**GEOPY-2153 - Increase length of possible string in value map**

GEOPY-2153: Increase length of possible string in value map

---

geoh5py/ui_json/ui_json.py

**GEOPY-2232 - Refactor components of inversion options**

GEOPY-2232: Refactor components of inversion options

---

geoh5py/data/referenced_data.py
geoh5py/shared/utils.py
tests/utils_test.py

**GEOPY-2258 - runing several times add_data_map + monitoring directory copy lead to error for inexisting data.**
Problems arise because data(1) was named data(1)(1) and no data(2)
And it tries to add an unknown entity_type, catch the eventual error

GEOPY-2258: runing several times add_data_map + monitoring directory copy lead to error for inexisting data.

---

geoh5py/shared/utils.py
tests/utils_test.py

**GEOPY-2292 - Use scientific format with fixed number of decimals to store means**
deal with no data values

GEOPY-2292: Use scientific format with fixed number of decimals to store means

---

geoh5py/ui_json/input_file.py
tests/ui_json_test.py
tests/ui_json_utils_test.py

**GEOPY-2121 - add the name of the application when saving ui.json**
override default uijson GA name for the title of the uijson

GEOPY-2121: add the name of the application when saving ui.json

---

geoh5py/data/visual_parameters.py
geoh5py/objects/vp_model.py
tests/vp_mesh_test.py

**GEOPY-2317 - Expose filter basement visual parameters to the VPmesh object.**
…model

GEOPY-2317: Expose filter basement visual parameters to the VPmesh object.

---

geoh5py/data/geometric_data.py
geoh5py/data/referenced_data.py
geoh5py/groups/property_group.py
geoh5py/objects/object_base.py
geoh5py/shared/entity_container.py
geoh5py/shared/utils.py
tests/reference_data_test.py

**GEOPY-2375 - Duplicated data map on re-run of domain mapper**
Now it should work
Not creating always a new GeometricData when copying but copying if needed. 
DataType has to be created everytime thought

GEOPY-2375: Duplicated data map on re-run of domain mapper

---

.github/workflows/python_analysis.yml
.github/workflows/python_deploy_dev.yml
.gitignore
.readthedocs.yml
geoh5py/__init__.py
poetry.lock
pyproject.toml
recipe.yaml
tests/version_test.py

**DEVOPS-545 - auto-versioning of Python packages**

DEVOPS-545: restore auto-versioning - unshallow for RTD

---

geoh5py/__init__.py
pylintrc
pyproject.toml
tests/version_test.py

**DEVOPS-545 - auto-versioning of Python packages**

DEVOPS-545: importlib

---

tests/drillhole_v4_0_test.py

**GEOPY-2423 - Investigate random failure of test on drillhole objects**

GEOPY-2423: Investigate random failure of test on drillhole objects

---

geoh5py/ui_json/forms.py
tests/ui_json/forms_test.py

**GEOPY-2459 - Support directoryOnly field in FileForm.**
…n restrictions.

GEOPY-2459: Support directoryOnly field in FileForm.

---

geoh5py/ui_json/forms.py
geoh5py/ui_json/ui_json.py
tests/ui_json/forms_test.py
tests/ui_json/uijson_test.py

**GEOPY-1875 - UIJson class: Infer Form type on read of ui.json file**
…er constructor, and storing inferred forms in a new extra property on uijson class.

GEOPY-1875: UIJson class: Infer Form type on read of ui.json file

---

geoh5py/ui_json/forms.py
geoh5py/ui_json/ui_json.py
tests/ui_json/forms_test.py
tests/ui_json/uijson_test.py

**GEOPY-1875 - UIJson class: Infer Form type on read of ui.json file**

GEOPY-1875
