.github/workflows/pytest-windows.yml

**GEOPY-175 - bring back codecov on geoh5py** 
can run on PR from forks

GEOPY-175: codecov token not necessary anymore

---

.github/workflows/pytest-unix-os.yml
.pre-commit-config.yaml

**GEOPY-258 - change required test platforms per branch** 
fixup for https://github.com/MiraGeoscience/geoh5py/pull/102

GEOPY-258: fixup github workfow file for Unix

---

geoh5py/io/h5_writer.py
geoh5py/workspace/workspace.py
tests/remove_root_test.py

**GEOPY-540 - UUID weakref crash if workspace_geoh5 present.**
Actual issue related to loading project tree recursively when the Root doesn't exist. Openning the workspace would always crash if Group/Objects were present. This was not an issue for new `geoh5` as always flat structures but would error loading the original `workspace_geoh5` file.
@sebhmg That's a pretty critical fix. Let's try to merge this in before you package again.

Fix opening workspace without a Root with groups

---

geoh5py/workspace/workspace.py
tests/remove_root_test.py

GEOPY-542: Root group did not include the children, resulting in an empty workspace on the second read.

GEOPY-542: root written without reference to children after creation

---

poetry.lock

**GEOPY-976 - vulnerability with pip**
to solve security alert with cryptography (https://github.com/MiraGeoscience/geoh5py/security/dependabot/18)
Ran:
poetry run pip install --upgrade pip
poetry lock --no-update

GEOPY-976: update version of pip

---

geoh5py/groups/property_group.py
tests/property_group_test.py

**GEOPY-1042 - cannot create several property groups**
An error was raised when a property group with no associated data was added to an object, and when the user tried to copy such object. 
Catch by verifying the input of properties.

catch properties bad instantiation when copying

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
geoh5py/shared/merging/base.py
tests/merger_test.py

This modification should handle both vertex and cell association. We might want to split the merge data into two methods (one for each), but the idea is there.

Simplify logic. Adjust tests to work on name AND type.name

---

geoh5py/ui_json/utils.py

**GEOPY-1106 - path2workspace, use Pathlib Path suffix**
use pathlib to get suffix instead of strings in path2workspace in ui.json utils

GEOPY-1106 - pathlib in ui.json utils

---

geoh5py/objects/surveys/direct_current.py
geoh5py/shared/__init__.py

**GEOPY-444 - Use logging instead of print**
Should we change warning to logger.warning?
Change from sprint 63 to sprint 62. I don't have the access

GEOPY-444: print replaced by logger

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml

**GEOPY-1129 - remove python 3.9 from pytest-unix-os github action**

GEOPY-1129 remove obsolete python version from github tests

---

geoh5py/objects/grid2d.py
geoh5py/objects/grid_object.py
geoh5py/objects/object_base.py
geoh5py/shared/concatenation.py
geoh5py/shared/utils.py
geoh5py/ui_json/utils.py
geoh5py/workspace/workspace.py
poetry.lock
tests/copy_entity_test.py
tests/monitored_update_test.py

**GEOPY-1148 - Geoh5py. GridObject.copy() => if PropertyGroup in children it raises an error**
In grid_object
Bug when copying grid_object containing a property group. Since propertygroups are contained in the children.
=> catch property groups with continue

GEOPY-1148: bug with grid.object.copy()

---

docs/content/release_notes.rst

**GEOPY-1161 - Release geoh5py 0.8.0rc2**

GEOPY-1161: Prep for rc2

---

geoh5py/objects/drillhole.py
geoh5py/shared/concatenation/concatenated.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/data.py
geoh5py/shared/concatenation/drillhole.py
geoh5py/shared/concatenation/object.py
geoh5py/workspace/workspace.py

**GEOPY-1321 - Change inheritance of ConcatenatedDrillholes**
change concatenation classes inheritance
I added "Data" to ConcatenatedData
I added "Base Object" to "Object"
To incorporate Drillhole on "ConcatenatedDrillhole", some changes had to be done in Drillholes
Is Concatenator Shouldn't be a DrillholeGroup inherited class?
Or an abstartc class at least with drillhole group Concateantor somewhere?

GEOPY-1321: Change inheritance of ConcatenatedDrillholes

---

geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/drillholes_group_table.py
tests/drillhole_v4_0_test.py

**GEOPY-1334 - improve drillholes tables memory and access*
update drillholes table based on Ben's comment:
- do not have the table on memory
- access the name directly, without loading everything
- update the concatenator data and index.

GEOPY-1335: improve drillholes tables memory and access

---

geoh5py/objects/surveys/direct_current.py
geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/tipper.py
geoh5py/shared/entity.py
tests/copy_entity_test.py
tests/metadata_test.py
tests/survey_dcip_test.py
tests/survey_fem_test.py
tests/survey_tem_test.py

**GEOPY-1364 - facilate metadata assignation to object**
update metadata to not rewrite everything and push to existing dictionary.
Change usage and inheritance of this function in geoh5py
Test everything
PS: my-py doesn't like super() functions, I ignore it.

GEOPY-1364: facilate metadata assignation to object

---

geoh5py/objects/geo_image.py
geoh5py/shared/conversion/geo_image.py
tests/geo_image_test.py

**GEOPY-1450 - Geoimage in geoh5py import tiff return black image**
Change the conversion from geoimage to grid, not converting data type anymore.
If the input image is a tiff, the data is automaticly duplicated as a grid

GEOPY-1450: Geoimage in geoh5py import tiff return black image

---

geoh5py/interfaces/api.pyi
geoh5py/interfaces/data.pyi
geoh5py/interfaces/groups.pyi
geoh5py/interfaces/objects.pyi
geoh5py/interfaces/shared.pyi
geoh5py/interfaces/workspace.pyi

**GEOPY-1481 - pylint runs on exclude folder geoh5py/interfaces and reports errors**

GEOPY-1481: pylint runs on exclude folder geoh5py/interfaces and reports errors

---

geoh5py/objects/object_base.py
tests/octree_test.py
tests/point_data_test.py

**GEOPY-1539 - Add a locations property to expose vertices or centroids on geoh5py.objects.ObjectBase**

GEOPY-1539: Add a locations property to expose vertices or centroids on geoh5py.objects.ObjectBase

---

geoh5py/data/numeric_data.py
tests/clip_vertex_data_test.py

**GEOPY-1541 - Protect against object associated data with array values**
(cherry picked from commit bc42b1bab28729ec06fc10454673f2c3bbcd0ae6)

GEOPY-1541: Protect against object associated data with array values

---

.github/workflows/pytest-unix-os.yml
.github/workflows/pytest-windows.yml
.github/workflows/static-analysis.yml
poetry.lock
pyproject.toml
tests/ui_json_test.py

**GEOPY-1619 - geo5py 3.9 for Python 3.12**

GEOPY-1619: allow python 3.11, 3.12, newer numpy and scipy

---

geoh5py/shared/entity.py
tests/metadata_test.py

**GEOPY-1770 - add a method to update metadata without rewriting everything**
add a new function "update_metadata" to entity

GEOPY-1770: add a method to update metadata without rewriting everything

---

.github/workflows/python_analysis.yml

**DEVOPS-471 - Merge windows and unix python reusable workflow in one file**
⚠️ Need to modify workflow reference `DEVOPS-471` to `DEVOPS-466` when `DEVOPS-471` gonna be merge in CI-Tools

DEVOPS-471: Merge windows and unix python reusable workflow in one file

---

geoh5py/ui_json/utils.py

**GEOPY-1719 - allow input active cells instead of topography**

GEOPY-1719: allow input active cells instead of topography

---

geoh5py/data/blob_data.py
geoh5py/data/data.py
geoh5py/data/primitive_type_enum.py
geoh5py/data/text_data.py
geoh5py/groups/property_group.py
geoh5py/groups/property_group_table.py
geoh5py/io/h5_writer.py
geoh5py/objects/cell_object.py
geoh5py/objects/object_base.py
geoh5py/shared/utils.py
tests/curve_data_test.py
tests/delete_entity_test.py
tests/grid_2d_test.py
tests/modify_property_group_test.py
tests/monitored_update_test.py
tests/point_data_test.py
tests/property_group_test.py
tests/remove_root_test.py
tests/utils_test.py

**GEOPY-1755 - create an object to access all the data of a property group in a recarray**
add a table for property group.
I used the same way to name the tables as "drillholes_group_table"
Still, I think it could be benificial in the future to name the property "table", 
the "[...]_table" "full" (or even __call__) and the "[...]_table form name" => "from_name()" for simplification for both usages.

GEOPY-1755: create an object to access all the data of a property group in a recarray

---

geoh5py/data/data.py
geoh5py/data/numeric_data.py
geoh5py/groups/property_group.py
geoh5py/groups/property_group_table.py
geoh5py/objects/cell_object.py
geoh5py/objects/notype_object.py
geoh5py/objects/object_base.py
geoh5py/objects/points.py
geoh5py/objects/surveys/electromagnetics/tipper.py
geoh5py/shared/concatenation/concatenator.py
geoh5py/shared/concatenation/drillhole.py
geoh5py/shared/merging/base.py
geoh5py/shared/merging/cell.py
geoh5py/shared/merging/drape_model.py
geoh5py/shared/merging/points.py
geoh5py/workspace/workspace.py
tests/curve_data_test.py
tests/delete_entity_test.py
tests/grid_2d_test.py
tests/point_data_test.py
tests/visual_parameters_test.py

**GEOPY-1669 - Final clean up of Object class**
I changed the object base a bit. 
I added some comments "#todo: ..." within the code. 
Can you comment back and then, and I'll correct/remove them if needed

GEOPY-1669: Final clean up of Object class

---

geoh5py/shared/utils.py
geoh5py/ui_json/utils.py
geoh5py/workspace/workspace.py

**GEOPY-1670 - cannot finalize workspace if tmp folder is not on the destination disk**
created a function, but I cannot create a unitest on it.
Guess the back and forth of testing will be there...

GEOPY-1670: change shutil move for copy

---

geoh5py/data/data_type.py
tests/data_instantiation_test.py

**GEOPY-1682 - Add new data_type attributes**
add new attributes.
/!\ Duplicate Type on copy is already used as a class attribute

GEOPY-1682: Add new data_type attributes

---

geoh5py/objects/block_model.py
tests/block_model_test.py

**GEOPY-1733 - Block model centroids not computed correctly for negative cell delimiters**

GEOPY-1733: Block model centroids not computed correctly for negative cell delimiters

---

geoh5py/data/data_type.py

**GEOPY-1798 - fail to open workspace due to data_type mapping epxected to be "cdf"**

GEOPY-1798: fail to open workspace due to data_type mapping epxected to be "cdf"

---

README.rst
docs/content/installation.rst
docs/content/release_notes.rst
package.rst

**GEOPY-1797 - wrong minimum Python version in geoh5py doc**

GEOPY-1797: wrong minimum Python version in geoh5py doc

---

geoh5py/shared/concatenation/concatenator.py

**GEOPY-1815 - Can't read DrillholeGroup with Strike/dip property_group_type**
avoid non compatible property_group to be present in drillholes-table

GEOPY-1815: Can't read DrillholeGroup with Strike/dip property_group_type

---

.github/workflows/python_deploy_dev.yml
.github/workflows/python_deploy_prod.yml

**DEVOPS-552 - Correct Pypi url in reusable-python-publish_pip_package.yml**
**relabel package publish tasks**
in scope of work for DEVOPS-552

DEVOPS-552: relabel package publish tasks

---

geoh5py/objects/surveys/electromagnetics/base.py
geoh5py/objects/surveys/electromagnetics/tipper.py
tests/survey_airborne_tem_test.py
tests/survey_fem_test.py
tests/survey_tipper_test.py

**GEOPY-1840 - Enforce reference data type shared between the tx_id_property of receiver and complement (transmitter, base station)**

GEOPY-1840: Enforce reference data type shared between the tx_id_property of receiver and complement (transmitter, base station)

---

geoh5py/groups/property_group.py
geoh5py/shared/concatenation/property_group.py

**GEOPY-1813 - Change typing for input PropertyGroup.properties to list[Data] | list[UUID] | list[str] instead list[Data | UUID | str]**
change the list type by Sequence as mypy don't like list

GEOPY-1813: Change typing for input PropertyGroup.properties to list[Data] | list[UUID] | list[str] instead list[Data | UUID | str]

---

geoh5py/objects/drillhole.py

**GEOPY-1932 - Desurveying can produce a divide by zero warning with some paths**

GEOPY-1932: Desurveying can produce a divide by zero warning with some paths

---

geoh5py/workspace/workspace.py

**GEOPY-1987 - Error from cmd.exe printed if h5repack is not found**

GEOPY-1987: Error from cmd.exe printed if h5repack is not found

---

geoh5py/shared/concatenation/drillholes_group_table.py

**GEOPY-2079 - petro-lingo composite bug when one of the association is selected**
Correct minors bugs in drillholes_table. 
linked with: https://github.com/MiraGeoscience/petro-lingo/compare/GEOPY-2079?expand=1

GEOPY-2079: petro-lingo composite bug when one of the association is selected

---

geoh5py/data/text_data.py

**GEOPY-2049 - new environment on development branches**
issue: arrays of types object when empty converted to STR by default for empty textdata

GEOPY-2049: new environment on development branches

---

geoh5py/ui_json/forms.py
tests/ui_json/forms_test.py

**GEOPY-2096 - ChoiceList parameters are converted to list when value is a string.**
…from the regular ChoiceForm.

GEOPY-2096: ChoiceList parameters are converted to list when value is a string.

---

geoh5py/data/referenced_data.py
geoh5py/objects/object_base.py
tests/reference_data_test.py
tests/text_data_test.py

**GEOPY-2301 - The fxmean attached to a referenced data is getting always the same name**
data_maps now  increment names
can be made public/private (default True => actual behavious)
tested.
I also add a text test to show you what I would like to do with petro-lingo. But we cannot visualize text data (when containing only 1 text) in GA...

GEOPY-2301: The fxmean attached to a referenced data is getting always the same name
